[PHP]
memory_limit = 512M
max_execution_time = 60
upload_max_filesize = 20M
post_max_size = 25M
display_errors = Off
display_startup_errors = Off
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
log_errors = On
error_log = /dev/stderr
expose_php = Off
date.timezone = Asia/Jakarta

[Date]
date.timezone = Asia/Jakarta
